export const SET_BURGER_MENU = 'SET_BURGER_MENU';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_MODAL_ADD_CARD = 'SET_MODAL_ADD_CARD';
export const SHOW_BUTTON_EXIT = 'SHOW_BUTTON_EXIT';